name: build

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
  schedule:
    - cron: "0 8 1 * *"

jobs:
  arduino:
    strategy:
      matrix:
        arduino-platform: ["arduino:samd", "arduino:avr"]
        include:
          - arduino-platform: "arduino:samd"
            fqbn: "arduino:samd:zero"
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}

      - name: Compile
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./examples/basic
